import XCTest
@testable import EAT_Network

final class MimeTypeTests: XCTestCase {
    
    func testMimeTypeRawValues() {
        XCTAssertEqual(MimeType.pdf.rawValue, "application/pdf")
        XCTAssertEqual(MimeType.png.rawValue, "image/png")
        XCTAssertEqual(MimeType.jpeg.rawValue, "image/jpeg")
        XCTAssertEqual(MimeType.gif.rawValue, "image/gif")
        XCTAssertEqual(MimeType.bmp.rawValue, "image/bmp")
        XCTAssertEqual(MimeType.svg.rawValue, "image/svg+xml")
        XCTAssertEqual(MimeType.mp4.rawValue, "video/mp4")
        XCTAssertEqual(MimeType.mov.rawValue, "video/quicktime")
        XCTAssertEqual(MimeType.avi.rawValue, "video/x-msvideo")
        XCTAssertEqual(MimeType.mkv.rawValue, "video/x-matroska")
        XCTAssertEqual(MimeType.webm.rawValue, "video/webm")
        XCTAssertEqual(MimeType.wav.rawValue, "audio/wav")
        XCTAssertEqual(MimeType.mp3.rawValue, "audio/mpeg")
        XCTAssertEqual(MimeType.ogg.rawValue, "audio/ogg")
        XCTAssertEqual(MimeType.flac.rawValue, "audio/flac")
        XCTAssertEqual(MimeType.txt.rawValue, "text/plain")
        XCTAssertEqual(MimeType.html.rawValue, "text/html")
        XCTAssertEqual(MimeType.css.rawValue, "text/css")
        XCTAssertEqual(MimeType.js.rawValue, "application/javascript")
        XCTAssertEqual(MimeType.json.rawValue, "application/json")
        XCTAssertEqual(MimeType.xml.rawValue, "application/xml")
        XCTAssertEqual(MimeType.csv.rawValue, "text/csv")
        XCTAssertEqual(MimeType.doc.rawValue, "application/msword")
        XCTAssertEqual(MimeType.docx.rawValue, "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
        XCTAssertEqual(MimeType.ppt.rawValue, "application/vnd.ms-powerpoint")
        XCTAssertEqual(MimeType.pptx.rawValue, "application/vnd.openxmlformats-officedocument.presentationml.presentation")
        XCTAssertEqual(MimeType.xls.rawValue, "application/vnd.ms-excel")
        XCTAssertEqual(MimeType.xlsx.rawValue, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        XCTAssertEqual(MimeType.zip.rawValue, "application/zip")
        XCTAssertEqual(MimeType.rar.rawValue, "application/vnd.rar")
        XCTAssertEqual(MimeType.tar.rawValue, "application/x-tar")
    }
    
    func testCustomMimeTypeRawValue() {
        let customType = "application/custom"
        let mimeType = MimeType.custom(customType)
        XCTAssertEqual(mimeType.rawValue, customType)
    }

    func testFilesExtensions() {
        XCTAssertEqual(MimeType.pdf.fileExtension, "pdf")
        XCTAssertEqual(MimeType.png.fileExtension, "png")
        XCTAssertEqual(MimeType.jpeg.fileExtension, "jpeg")
        XCTAssertEqual(MimeType.gif.fileExtension, "gif")
        XCTAssertEqual(MimeType.bmp.fileExtension, "bmp")
        XCTAssertEqual(MimeType.svg.fileExtension, "svg")
        XCTAssertEqual(MimeType.mp4.fileExtension, "mp4")
        XCTAssertEqual(MimeType.mov.fileExtension, "mov")
        XCTAssertEqual(MimeType.avi.fileExtension, "avi")
        XCTAssertEqual(MimeType.mkv.fileExtension, "mkv")
        XCTAssertEqual(MimeType.webm.fileExtension, "webm")
        XCTAssertEqual(MimeType.wav.fileExtension, "wav")
        XCTAssertEqual(MimeType.mp3.fileExtension, "mp3")
        XCTAssertEqual(MimeType.ogg.fileExtension, "ogg")
        XCTAssertEqual(MimeType.flac.fileExtension, "flac")
        XCTAssertEqual(MimeType.txt.fileExtension, "txt")
        XCTAssertEqual(MimeType.html.fileExtension, "html")
        XCTAssertEqual(MimeType.css.fileExtension, "css")
        XCTAssertEqual(MimeType.js.fileExtension, "js")
        XCTAssertEqual(MimeType.json.fileExtension, "json")
        XCTAssertEqual(MimeType.xml.fileExtension, "xml")
        XCTAssertEqual(MimeType.csv.fileExtension, "csv")
        XCTAssertEqual(MimeType.doc.fileExtension, "doc")
        XCTAssertEqual(MimeType.docx.fileExtension, "docx")
        XCTAssertEqual(MimeType.ppt.fileExtension, "ppt")
        XCTAssertEqual(MimeType.pptx.fileExtension, "pptx")
        XCTAssertEqual(MimeType.xls.fileExtension, "xls")
        XCTAssertEqual(MimeType.xlsx.fileExtension, "xlsx")
        XCTAssertEqual(MimeType.zip.fileExtension, "zip")
        XCTAssertEqual(MimeType.rar.fileExtension, "rar")
        XCTAssertEqual(MimeType.tar.fileExtension, "tar")
        XCTAssertEqual(MimeType.custom("custom").fileExtension, "custom")
    }
}
